In [12]:
from matplotlib.pyplot import cm
import numpy as np
import matplotlib.pyplot as plt
%matplotlib ipympl
#plt.style.use('default')
plt.style.use('seaborn')
from matplotlib import rcParams
rcParams['axes.titley'] = 1.1

plt.rcParams['figure.constrained_layout.use'] = True
plt.rcParams['figure.constrained_layout.h_pad'] = 0.1
plt.rcParams['figure.constrained_layout.w_pad'] = 0.1

In [2]:
from __future__ import print_function, division
import sys,os
# line 4 and line 5 below are for development purposes and can be removed
qspin_path = os.path.join(os.getcwd(),"../../")
sys.path.insert(0,qspin_path)
#####################################################################
#                            example 0                              #
#    In this script we demonstrate how to use QuSpin's exact        #
#    diagonlization routines to solve for the eigenstates and       #
#    energies of the XXZ chain.                                     #
#####################################################################
from quspin.operators import hamiltonian # Hamiltonians and operators
from quspin.basis import spin_basis_1d # Hilbert space spin basis
import numpy as np # generic math functions
#
##### define model parameters #####
L=4 # system size
Jxy=0; #p.sqrt(2.0) # xy interaction
Jzz_0=1.0 # zz interaction
hz=0.0/np.sqrt(3.0) # z external field
#
##### set up Heisenberg Hamiltonian in an external z-field #####
# compute spin-1/2 basis
#basis = spin_basis_1d(L,pauli=False)
#basis = spin_basis_1d(L,pauli=False,Nup=L//2) # zero magnetisation sector
basis = spin_basis_1d(L,pauli=False,Nup=L//2,pblock=1) # and positive parity sector
# define operators with OBC using site-coupling lists
J_zz = [[Jzz_0,i,i+1] for i in range(L-1)] # OBC
J_xy = [[Jxy/2.0,i,i+1] for i in range(L-1)] # OBC
h_z=[[hz,i] for i in range(L)]
# static and dynamic lists
static = [["+-",J_xy],["-+",J_xy],["zz",J_zz],["z",h_z]]
dynamic=[]
# compute the time-dependent Heisenberg Hamiltonian
H_XXZ = hamiltonian(static,dynamic,basis=basis,dtype=np.float64)
#
##### various exact diagonalisation routines #####
# calculate entire spectrum only
E=H_XXZ.eigvalsh()
# calculate full eigensystem
E,V=H_XXZ.eigh()
print(E,'\n',V)

Hermiticity check passed!
Symmetry checks passed!
Particle conservation check passed!
[-0.75 -0.25 -0.25  0.25] 
 [[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
print(basis.get_proj(dtype=np.float64))
print(H_XXZ.as_dense_format())

In [11]:
plt.figure()
plt.plot(E)
plt.show()

[-5.14209063e+00 -4.51329095e+00 -4.40782917e+00 -4.00991280e+00
 -3.91842456e+00 -3.87312493e+00 -3.79175211e+00 -3.70133971e+00
 -3.58079260e+00 -3.44362021e+00 -3.44349578e+00 -3.40205834e+00
 -3.38039033e+00 -3.27518885e+00 -3.20191037e+00 -3.17836475e+00
 -3.12952448e+00 -3.12149082e+00 -3.09912124e+00 -3.07938009e+00
 -2.94838868e+00 -2.92710829e+00 -2.82555952e+00 -2.81576057e+00
 -2.81500095e+00 -2.78254749e+00 -2.76989628e+00 -2.72869237e+00
 -2.71471564e+00 -2.68966130e+00 -2.63524821e+00 -2.60780993e+00
 -2.58440751e+00 -2.57805890e+00 -2.52871651e+00 -2.50985863e+00
 -2.50204986e+00 -2.45992850e+00 -2.44487733e+00 -2.38722712e+00
 -2.37925105e+00 -2.37767390e+00 -2.37537605e+00 -2.33974886e+00
 -2.33072767e+00 -2.28487788e+00 -2.27892172e+00 -2.22666431e+00
 -2.21125325e+00 -2.20593693e+00 -2.20260853e+00 -2.17013088e+00
 -2.15803468e+00 -2.14995359e+00 -2.09953226e+00 -2.07967811e+00
 -2.07687831e+00 -2.07130575e+00 -2.06705578e+00 -2.00170313e+00
 -1.99311591e+00 -1.99014

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [5]:
# calculate minimum and maximum energy only
Emin,Emax=H_XXZ.eigsh(k=2,which="BE",maxiter=1E4,return_eigenvectors=False)
# calculate the eigenstate closest to energy E_star
E_star = 0.0
E,psi_0=H_XXZ.eigsh(k=1,sigma=E_star,maxiter=1E4)
psi_0=psi_0.reshape((-1,))

# Code from 
* [https://ryanlevy.github.io/physics/Heisenberg1D-ED/](https://ryanlevy.github.io/physics/Heisenberg1D-ED/)

In [4]:
#Constants of the problem
L   = 10
Jxy = -1     # when J<0 it is antiferromagnetic 
Jz  = -1     # J_z = J_xy = J is the normal Heisenberg model instead of XXZ model
h   = -0e-5 # small h field to break degeneracy
generatePlots(L,Jxy,Jz,h)


L = 10 basis size: 1024
Energies assembled!
Lowest energy: -4.515446354492041
The ground state occured in Sz= 0


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

====
L = 10 basis size: 1024
The biggest states are:
|↓|↑|↓|↑|↓|↑|↓|↑|↓|↑|
|↑|↓|↑|↓|↑|↓|↑|↓|↑|↓|


In [5]:
lowestEnergy,GSSector,GSEigenvector,energies=getSpectrum(2,0,-1,0)
for i in energies:
    print(i)

L = 2 basis size: 4
Energies assembled!
Lowest energy: -0.5
The ground state occured in Sz= 0
[0.5]
[-0.5 -0.5]
[0.5]


In [14]:
#Constants of the problem
%matplotlib ipympl
L   = 12
Jxy = 1     # when J<0 it is antiferromagnetic 
Jz  = 1     # J_z = J_xy = J is the normal Heisenberg model instead of XXZ model
h   = -1e-5 # small h field to break degeneracy
generatePlots(L,Jxy,Jz,h)


L = 12 basis size: 4096
Energies assembled!
Lowest energy: -3.0
The ground state occured in Sz= -12


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

====
L = 12 basis size: 4096
The biggest states are:
|↓|↓|↓|↓|↓|↓|↓|↓|↓|↓|↓|↓|


In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as spst

def basisVisualizer(L,psi):
    '''Given psi=(#)_10, outputs the state in arrows'''
    #ex: |↓|↑↓|↑|↑|
    psi_2 = bin(psi)[2:]
    N  = len(psi_2)
    up = (L-N)*'0'+psi_2
    configStr = "|"
    uparrow   = '\u2191'
    downarrow = '\u2193'
    for i in range(L):
        blank = True
        if up[i] == '1':
            configStr+=uparrow
            blank = False
        if up[i] == '0':
            configStr+=downarrow
            blank = False
        if blank:
            configStr+="_"
        configStr +="|"
    print(configStr)
def countBits(x):
    '''Counts number of 1s in bin(n)'''
    #From Hacker's Delight, p. 66
    x = x - ((x >> 1) & 0x55555555)
    x = (x & 0x33333333) + ((x >> 2) & 0x33333333)
    x = (x + (x >> 4)) & 0x0F0F0F0F
    x = x + (x >> 8)
    x = x + (x >> 16)
    return x & 0x0000003F 
#helper function to print binary numbers
def binp(num, length=4):
    '''print a binary number without python 0b and appropriate number of zeros'''
    return format(num, '#0{}b'.format(length + 2))[2:]

def makeSzBasis(L):
    basisSzList = [[] for i in range(0,2*L+1,2)] #S_z can range from -L to L, index that way as well
    #this is probably a bad way to do it
    # count bits is O(log(n)) and loop is O(2**L) :(
    for i in range(2**L):
        Szi = 2*countBits(i) - L
        basisSzList[(Szi+L)//2].append(i)
    print("L =",L,"basis size:",2**L)
    return basisSzList


def makeH(SzList,L,Jxy,Jz,h):
    '''Make a 1D Heisenberg chain of length L with Jxy,Jz and magnetic field h out of an SzList of states'''
    
    basisMap = {}
    stateID  = 0 
    #generate an ordering
    for state in SzList:
        #print(state) #basisVisualizer(L,state)
        basisMap[state] = stateID
        stateID+=1
    nH = stateID
    H = np.zeros([nH,nH])
    #now fill H
    for state in SzList:
        idxA = basisMap[state]
        H[idxA,idxA] += -h*countBits(state) # B field
        for i in range(L):
            j = (i+1)%L #nearest neighbors are hard coded here
            if (state>>i & 1) == (state>>j & 1):#matching bit check
                H[idxA,idxA] += -Jz/4
            else:
                H[idxA,idxA] -= -Jz/4
                mask = 2**(i)+2**j
                stateB= state^mask #this flips the bits at i,j
                idxB = basisMap[stateB]
                H[idxA,idxB]+= -Jxy/2
    #print(np.all(H==H.T)) #check if Hermitian and is coded properly; very slow
    return H

def getSpectrum(L,Jxy,Jz,h):
    '''Returns lowestEnergy, 
               Sz sector of the GS, 
               GS eigenvector, 
               and all energies'''
    basisSzList  = makeSzBasis(L)
    energies     = []
    lowestEnergy = 1e10
    
    for Szi,SzList in enumerate(basisSzList):
        #print('=============')
        #print("Sz sector:",-L+2*Szi)
        #print('=============')
        H     = makeH(SzList,L,Jxy,Jz,h)
        lam,v = np.linalg.eigh(H)
        energies.append(lam)
        #keep track of GS
        if min(lam) < lowestEnergy:
            lowestEnergy  = min(lam)
            GSSector      = -L+2*Szi
            GSEigenvector = v[:,lam.argmin()]
    
    print("Energies assembled!")
    print("Lowest energy:",lowestEnergy)
    print("The ground state occured in Sz=",GSSector)
    return (lowestEnergy,GSSector,GSEigenvector,energies)

def generatePlots(L,Jxy,Jz,h):
    (lowestEnergy,GSSector,
     GSEigenvector,energies) = getSpectrum(L,Jxy,Jz,h)
    total_energies = [en for szlist in energies for en in szlist]
    maxE           = np.max(total_energies)
    offset = 0
    for i in range(len(energies)):
        plt.plot(range(offset,len(energies[i])+offset),energies[i],'o')
        offset+=len(energies[i])
        if len(energies)-4>i>2:
            if i%2==0:
                plt.text(offset-200,maxE+1,"Sz="+str(-L+2*i))
            else:
                plt.text(offset-200,maxE+0.5,"Sz="+str(-L+2*i))

    plt.xlabel("Arbitrary Order",fontsize=15)
    plt.ylim([lowestEnergy-0.5,maxE+2])
    plt.ylabel("Energy",fontsize=15)
    plt.title(r"XXZ model with $L="+str(L)+",\,\,\, J_z="+str(Jz)+",\,\,\, J_{xy}="+str(Jxy)+"$",fontsize=15)
    plt.plot([0,offset],[lowestEnergy,lowestEnergy],'--',label="Ground State")
    plt.legend(loc='lower right')
    plt.show()
    print('====')
    plt.plot(GSEigenvector,'o-')
    plt.xlabel("state order",fontsize=15)
    plt.ylabel(r"$|\psi_0\rangle$",fontsize=15)
    plt.title("Ground State Eigenvector \nwith $L="+str(L)+",\,\,\, J_z="+str(Jz)+",\,\,\, J_{xy}="+str(Jxy)+"$",fontsize=15)
    plt.show()
    
    basisSzList   = makeSzBasis(L)
    GSEigenvector = np.abs(np.round(GSEigenvector,10)) #rounding errors
    bigStatesID   = np.argwhere(np.abs(GSEigenvector) == np.max((GSEigenvector))).reshape((1,-1))
    
    #Get the states
    print("The biggest states are:")
    for state in bigStatesID[0]:
        bigStates = basisSzList[(GSSector+L)//2][state]
        basisVisualizer(L,bigStates)
        